const courses = [
    { name: "市場と経済", credits: 2, staminaCost: 20, annual: false },
    { name: "統計学", credits: 2, staminaCost: 30, annual: false },
    { name: "政治学", credits: 2, staminaCost: 20, annual: false },
    { name: "社会学", credits: 2, staminaCost: 10, annual: false },
    { name: "心理学", credits: 2, staminaCost: 20, annual: false },
    { name: "情報", credits: 2, staminaCost: 10, annual: false },
    { name: "憲法", credits: 2, staminaCost: 30, annual: false },
    { name: "日本史", credits: 2, staminaCost: 10, annual: false },
    { name: "ミクロ経済学", credits: 2, staminaCost: 20, annual: false },
    { name: "マクロ経済学", credits: 2, staminaCost: 20, annual: false },
    { name: "行政学", credits: 2, staminaCost: 20, annual: false },
    { name: "地方自治論", credits: 2, staminaCost: 20, annual: false },
    { name: "国際政治", credits: 2, staminaCost: 20, annual: false },
    { name: "社会調査法", credits: 2, staminaCost: 20, annual: false },
    { name: "メディア論", credits: 2, staminaCost: 10, annual: false },
    { name: "コミュニケーション論", credits: 2, staminaCost: 10, annual: false },
    { name: "教育学", credits: 2, staminaCost: 20, annual: false },
    { name: "労働政策", credits: 2, staminaCost: 20, annual: false },
    { name: "法学概論", credits: 2, staminaCost: 20, annual: false },
    { name: "民法", credits: 2, staminaCost: 30, annual: false },
    { name: "経営学", credits: 2, staminaCost: 20, annual: false },
    { name: "会計学", credits: 2, staminaCost: 30, annual: false },
    { name: "データ分析", credits: 2, staminaCost: 30, annual: false },
    { name: "情報社会論", credits: 2, staminaCost: 10, annual: false },
    { name: "哲学", credits: 2, staminaCost: 10, annual: false },
    { name: "倫理学", credits: 2, staminaCost: 10, annual: false },
    { name: "地域政策", credits: 2, staminaCost: 20, annual: false },
    { name: "政治思想", credits: 2, staminaCost: 30, annual: false },
    { name: "行政法", credits: 2, staminaCost: 40, annual: false },
    { name: "財政学", credits: 2, staminaCost: 30, annual: false },
    { name: "社会政策", credits: 2, staminaCost: 20, annual: false },
    { name: "公共政策", credits: 2, staminaCost: 30, annual: false },
    { name: "労働法", credits: 2, staminaCost: 40, annual: false },
    { name: "マーケティング論", credits: 2, staminaCost: 20, annual: false },
    { name: "地域社会論", credits: 2, staminaCost: 30, annual: false },
    { name: "公共経済学", credits: 2, staminaCost: 50, annual: false },
    { name: "政治哲学", credits: 2, staminaCost: 30, annual: false },
    { name: "メディア法", credits: 2, staminaCost: 40, annual: false },
    { name: "人類学", credits: 2, staminaCost: 30, annual: false },
    { name: "法社会学", credits: 2, staminaCost: 20, annual: false },
    { name: "ジェンダー論", credits: 2, staminaCost: 30, annual: false },
    { name: "自然科学", credits: 2, staminaCost: 40, annual: false },
    { name: "民俗学", credits: 2, staminaCost: 20, annual: false },
    { name: "考古学", credits: 2, staminaCost: 30, annual: false },
    { name: "中国語", credits: 2, staminaCost: 50, annual: false },
    { name: "ドイツ語", credits: 4, staminaCost: 40, annual: true },
    { name: "基礎演習", credits: 4, staminaCost: 30, annual: true, requiredYear: 1 },
    { name: "英語", credits: 2, staminaCost: 20, annual: false, requiredYear: 1 },
    { name: "専門演習", credits: 4, staminaCost: 30, annual: false, requiredYear: 2 },
    { name: "卒業論文演習", credits: 4, staminaCost: 40, annual: true, requiredYear: 3 },
    { name: "卒業研究", credits: 4, staminaCost: 40, annual: true, requiredYear: 4 },
];
